version: '3'

services:

  web:
    image: nginx:alpine
    container_name: example-webapp
    expose:
      - "80"
    environment:
      VIRTUAL_HOST: www.example.com
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: www.example.com
      LETSENCRYPT_EMAIL: mail@example.com
    restart: always


networks:
  default:
    external:
      name: nginx-proxy
